config/routes.rb
Rails.application.routes.draw do
	 devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get 'contacts/upload', to: 'contacts#upload', as: 'upload'
	post 'contacts/import', to: 'contacts#import', as: 'import_create'

  resources :contacts do
		resources :gifts
	end

	resources :lists
	resources :groups
	resources :gifts

	get '/dashboard', to: 'dashboard#index', as: 'dashboard'

	authenticated :user do
		root 'dashboard#index', as: :authenticated_root
	end

	root to: 'pages#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
		@contacts_count = current_user.contacts.count
		@lists_count = current_user.lists.count
		@gifts_count = current_user.gifts.count
		@lists = current_user.lists.all
    @birthdays = current_user.contacts.where("birthday_month >= ? AND birthday_month <= ?", Time.now.month, (Time.now + 1.month).month).order(:birthday_month)
end

end

app/views/dashboard/index.html.erb
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Contacts</p>
          <p class="title"><%= @contacts_count %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Gifts</p>
          <p class="title"><%= @gifts_count %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Lists</p>
          <p class="title"><%= @lists_count %></p>
        </div>
      </div>
    </nav>

    <hr>

    <div class="columns">
      <div class="column is-6 birthdays">
        <h3>Upcoming Birthdays</h3>
        <% @birthdays.each do |b| %>
          <div><%= b.first_name %> <%= b.last_name %>: <%= Date::MONTHNAMES[b.birthday_month] %> <%= b.birthday_day %></div>
        <% end %>
      </div>
      <hr>
      <div class="column is-6">
      <h2>Gift Lists</h2>
        <% @lists.each do |l| %>
          <div><%= link_to l.name, list_path(l) %></div>
        <% end %>
      </div>
    </div>