config/routes.rb
Rails.application.routes.draw do
	 devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get 'contacts/upload', to: 'contacts#upload', as: 'upload'
	post 'contacts/import', to: 'contacts#import', as: 'import_create'

  resources :contacts do
		resources :gifts
	end

	resources :lists
	resources :groups
	resources :gifts

	get '/dashboard', to: 'dashboard#index', as: 'dashboard'

	authenticated :user do
		root 'dashboard#index', as: :authenticated_root
	end

	root to: 'pages#home'
end

app/models/gift.rb
class Gift < ApplicationRecord
	belongs_to :user
	belongs_to :contact

	default_scope { includes(:contact) }
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController

	before_action :authenticate_user!

	def index
		@gifts = current_user.gifts
	end

	def new
		@gift = Gift.new
	end

	def show
		@gift = Gift.find(params[:id])
	end

	def edit
		@gift = Gift.find(params[:id])
	end

	def update
		@gift = Gift.find(params[:id])
		respond_to do |format|
			if @gift.update(gift_params)
				format.html { redirect_to gifts_path, notice: 'Gift was successfully updated.' }
			else
				format.html { render :edit, notice: "Uh oh, something went wrong" }
			end
		end
	end

	def destroy
		@gift = Gift.find(params[:id])
		@gift.destroy
		redirect_to gifts_path
	end

		def create
			@gift = current_user.gifts.new(gift_params)

			respond_to do |format|
				if @gift.save
					format.html { redirect_to gifts_path, notice: "Your gift was added. Gosh, so generous" }
				else
					format.html { redirect_to gifts_path, notice: "Uh oh, something went wrong " }
				end
			end
		end

		def gift_params
			params.require(:gift).permit(:title, :url, :contact_id)
		end


end

app/views/gifts/_form.html.erb
    <%= form_for @gift do |f| %>

		<div class="field control">
			<label>Contact</label>
			<%= collection_select(:gift, :contact_id, Contact.all, :id, :first_name) %> <br>
	</div>


    <div class="field control">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'input' %>
    </div>

      <div class="field control">
      <%= f.label :url %>
      <%= f.text_field :url, class: 'input' %>
    </div>

      <div class="field control">
      <%= f.submit 'Save', class: 'button is-primary' %>
    </div>
    <% end %>

app/views/gifts/edit.html.erb
<section class="container dashboard">
  <div class="content box">
		<div class="container content">
			<h1> Edit Gift </h1>

		</div>

    <%= render 'form' %>

  

	</div>
</section>

app/views/gifts/index.html.erb
<div class="add-contact-button">
	<%= link_to "Add New Gift", new_gift_path, method: :get, class: 'button is-primary' %>
</div>


	<h2>Current Gifts</h2>

			<table class="table is-fullwidth" id="gifts-table">
				<thead>
					<tr>
						<th>Gift Title</th>
						<th>Who's it for?</th>
						<th>Gift URL</th>
						<th>Edit</th>
						<th>Delete?</th>
					</tr>
				</thead>
				<tbody>
				<% @gifts.each do |gift| %>
					<tr>
						<td><%= gift.title %></td>
						<td><%= gift.contact.first_name%> <%= gift.contact.last_name %></td>
						<td><%= gift.url %></td>
						<td><%= link_to "Edit", edit_gift_path(gift.id) %></td>
						<td><%= link_to "Delete", gift_path(gift.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>

app/views/gifts/new.html.erb
<div class="container content">
				<h1> Add New Gift </h1>
</div>

<%= render 'form' %>

app/views/gifts/show.html.erb
<%= @gift.inspect %>