config/routes.rb
Rails.application.routes.draw do
	 devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get 'contacts/upload', to: 'contacts#upload', as: 'upload'
	post 'contacts/import', to: 'contacts#import', as: 'import_create'

  resources :contacts do
		resources :gifts
	end

	resources :lists
	resources :groups
	resources :gifts

	get '/dashboard', to: 'dashboard#index', as: 'dashboard'

	authenticated :user do
		root 'dashboard#index', as: :authenticated_root
	end

	root to: 'pages#home'
end

app/models/contact.rb
class Contact < ApplicationRecord
	require 'csv'

	validates_presence_of :first_name, :last_name

	belongs_to :user
	belongs_to :group, optional: true
	has_many :gifts, dependent: :destroy
	has_and_belongs_to_many :lists

	accepts_nested_attributes_for :gifts, :allow_destroy => true

	scope :group_filter, -> (group) { where('groups.title = ?', group) }

	def self.import(file)
		# a block the runs through a loop in our CSV data

		CSV.foreach(file.path, headers: true, :header_converters => :symbol ) do |row|
		# creates a user for each row in the CSV file
		Contact.create! row.to_hash
end
end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user!

  def index
    puts params[:group]
    @groups = current_user.groups
    if params[:group].blank?
      @contacts = current_user.contacts.includes(:group).all.order(:last_name)
    else
    @contacts = Contact.joins(:group).where('groups.title = ?', params[:group])
  end
    respond_to do |format|
      format.html
      format.json { render json: @contacts }
  end
  end

  def upload
    @contacts = current_user.contacts.all
  end

  def import
    current_user.contacts.import(params[:file])
    redirect_to contacts_path, notice: 'Data Imported!'
  end

  def create
    @contact = current_user.contacts.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_path, notice: "Your contact has been added. You're so neat!" }
        format.json { render :json => @contact.to_json, status: :created, location: @contact }
      else
        format.html { render :new, notice: "Uh oh, something went wrong" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @contact = Contact.new
  end

  def edit
    @groups = Group.all
  	@contact = Contact.includes(:group).find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
  	if @contact.update(contact_params)
  		format.html { redirect_to contacts_path, notice: 'Contact was successfully updated.' }
      format.json { render :json => @contact.to_json, status: :ok, location: @contact }
  	else
      format.html { render :edit, notice: "Uh oh, something went wrong" }
      format.json { render json: @contact.errors, status: :unprocessable_entity }
  	end
  end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path
  end

  def show
    @contact = Contact.includes(:gifts).find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:id, :user_id, :group_id, :notes, :first_name, :last_name, :birthday_day, :birthday_month, :wedding_anniversary, :address, gifts_attributes: [:user_id, :id, :title, :image, :contact_id, :url, :_destroy])
  end

end

app/helpers/contact_helper.rb
module ContactHelper

	def get_month(date)
		Date::MONTHNAMES[date]
	end

end

app/views/contacts/_edit.html.erb
<%= form_for @contact do |f| %>

	<div class="field control">
		<label>First Name</label>
		<%= f.text_field :first_name, class: 'input' %>
	</div>

	<div class="field control">
	<label>Last Name</label>
	<%= f.text_field :last_name, class: 'input' %>
	</div>

	<div class="field control">
		<label>Group</label>
		<%= f.collection_select :group_id, Group.all, :id, :title %>
	</div>

		<div class="field control">
			<label>Birthday</label>
	
			<%= f.select :birthday_day, options_for_select(0..31) %>
	</div>

	<div class="field control">
		<label>Address</label>
		<%= f.text_field :address, class: 'input' %>
	</div>

	<div class="field control">
		<label>Notes</label>
		<%= f.text_area :notes, class: 'textarea' %>
	</div>

<!-- <h2>Gifts</h2>

<div v-for="(gift, index) in contact.gifts_attributes">

	<div v-if="gift._destroy != '1'" class="field has-addons">


		<div class="field is-horizontal">

		<input type="text" placeholder="gift title" class="input" v-model="gift.title" />
		<input type="text" id="gift-url" placeholder="url" class="input" v-model="gift.url" />
	</div>
	<div class="control">
		<button class="button" v-on:click="removeGift(index)">Delete Gift</button>
	</div>
	</div>
</div>
<br>
<button class="button" v-on:click="addGift">Add Gift</button>

<br>
<br> -->
<%= f.submit "Save", class: 'button is-primary' %>

<% end %>

</div>

app/views/contacts/_form.html.erb
<div class="container is-fluid">

  <%= form_for @contact do |f| %>

    <div class="field control">
      <label>First Name</label>
      <%= f.text_field :first_name, class: 'input' %>
    </div>

    <div class="field control">
    <label>Last Name</label>
    <%= f.text_field :last_name, class: 'input' %>
    </div>

    <div class="field control">
      <label>Group</label>
      <%= f.collection_select :group_id, Group.all, :id, :title %>
    </div>

      <div class="field control">
        <label>Birthday</label>
        <%= f.date_select :birthday_month, { discard_year: true, discard_day: true } %>
        <%= f.select :birthday_day, options_for_select(0..31) %>
    </div>

    <div class="field control">
      <label>Address</label>
      <%= f.text_field :address, class: 'input' %>
    </div>

    <div class="field control">
      <label>Notes</label>
      <%= f.text_area :notes, class: 'textarea' %>
    </div>

  <!-- <h2>Gifts</h2>

  <div v-for="(gift, index) in contact.gifts_attributes">

    <div v-if="gift._destroy != '1'" class="field has-addons">


      <div class="field is-horizontal">

      <input type="text" placeholder="gift title" class="input" v-model="gift.title" />
      <input type="text" id="gift-url" placeholder="url" class="input" v-model="gift.url" />
    </div>
    <div class="control">
      <button class="button" v-on:click="removeGift(index)">Delete Gift</button>
    </div>
    </div>
  </div>
  <br>
  <button class="button" v-on:click="addGift">Add Gift</button>

  <br>
  <br> -->
<%= f.submit "Save", class: 'button is-primary' %>

  <% end %>

  </div>

</section>

app/views/contacts/_gift_fields.html.erb
<div class="columns">
	<div class="column">
		<div class="field control">
      <%= f.label :title, 'Gift' %>
      <%= f.text_field :title, class: 'input' %>
    </div>
</div>
	<div class="column">
    <div class="field control">
      <%= f.label :url, 'URL' %>
      <%= f.text_field :url, class: 'input' %>
    </div>
	</div>

</div>

app/views/contacts/_show.html.erb
<h1><%=  @contact.first_name %> <%= @contact.last_name %></h1>
	<p>Birthday: <%= get_month(@contact.birthday_month) %> <%= @contact.birthday_day %>
	<p>Address: <%= @contact.address %></p>
	<p>Group: <%= @contact.group.title rescue 'None' %>
	<p>Notes: <%= @contact.notes %></p>

<h2>Gifts</h2>
	<ul>
		<% @contact.gifts.each do |gift| %>
			<li><%= gift.title %>: <a href=" <%=gift.url %>"><%= gift.url %></a></li>
		<% end %>
	</ul>
	<%= link_to "Edit", edit_contact_path(@contact.id), data: {remote: true }, class: 'button is-primary' %>
	<%= link_to "Delete", contact_path(@contact.id), method: :delete, class: 'button is-danger', data: {confirm: "Are you sure?"} %>
</div>

app/views/contacts/edit.html.erb
<section class="container dashboard">
  <div class="content box">
		<div class="container content">
			<h1> Edit Contact </h1>
		</div>
		<%= render 'form' %>
	</div>
</section>

app/views/contacts/edit.js.erb
var c = document.querySelector('#contact-card');
c.innerHTML = "<%= j render 'edit' %>"

app/views/contacts/index.html.erb
<div id="contact-page">
<div class="columns">
  <div class="column is-3">
    <div class="box">
    <div class="group-list">
          <%= link_to "Add New Contact", new_contact_path, method: :get, class: 'button is-primary' %><br>
      <button><%= link_to "All", contacts_path() %></button>
      <% @groups.each do |g| %>
      <p><button><%= link_to g.title, contacts_path(:group => g.title) %></button></p>
      <% end %>
    </div>
  </div>
  </div>

  <div class="column is-4">
    <div class="box">
    <div style="overflow-y:scroll; overflow-x:hidden; height:400px;" id="contacts">
      <h2 class="title">Contacts</h2>
      <nav class="panel">
      <% @contacts.each do |c| %>
      <%= link_to "#{c.first_name}" "#{c.last_name}", contact_path(c.id), data: { remote: true }, class: 'panel-block contact-panel' %>
        <% end %>

  </div>
</nav>
</div>

</div>

<div class="column is-5">
  <div id="contact-card" class="box">
    <p>hello</p>
  </div>
</div>
</div>
</div>

app/views/contacts/new.html.erb
<div class="container content">
				<h1> Add New Contact </h1>
</div>

<%= render 'form' %>

app/views/contacts/show.html.erb
<section class="container contacts-show">
  <div class="content box">
		<h1><%=  @contact.first_name %> <%= @contact.last_name %></h1>
			<p>Birthday: <%= get_month(@contact.birthday_month) %> <%= @contact.birthday_day %>
			<p>Address: <%= @contact.address %></p>
      <p>Group: <%= @contact.group.title rescue 'None' %>
      <p>Notes: <%= @contact.notes %></p>

		<h2>Gifts</h2>
			<ul>
				<% @contact.gifts.each do |gift| %>
					<li><%= gift.title %>: <a href=" <%=gift.url %>"><%= gift.url %></a></li>
				<% end %>
			</ul>
			<%= link_to "Edit", edit_contact_path(@contact.id), class: 'button is-primary' %>
			<%= link_to "Delete", contact_path(@contact.id), method: :delete, class: 'button is-danger', data: {confirm: "Are you sure?"} %>
	</div>

</div>
</section>

app/views/contacts/show.js.erb
	var contact = document.querySelector('#contact-card');
	contact.innerHTML = "<%= j render 'show' %>"

app/views/contacts/upload.html.erb
<section class="container">
	<div class="content box">
		<div class="content is-centered">
			<h2> Import data </h2>
				<%= form_tag import_create_path, multipart: true do %>
					<%= file_field_tag :file %>
					<%= submit_tag "Import CSV" %>
				<% end %>
			</div>

			<div class="contacts-table">
				<h2>Imported Contacts</h2>
			<table class="table" id="contacts-table">
				<thead>
					<tr>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Address</th>
						<th>Birthday</th>
						<th>View</ht>
					</tr>
				</thead>
				<tbody>
				<% @contacts.each do |contact| %>
					<tr>
						<td><%= contact.first_name %></td>
						<td><%= contact.last_name %></td>
						<td><%= contact.address %></td>
						<td> <%= Date::MONTHNAMES[contact.birthday_month] %> <%= contact.birthday_day %></td>
						<td><%= link_to "View", contact_path(contact) %>
					</tr>
				<% end %>
				</tbody>
			</table>
		</div>
	</div>
</section>