config/routes.rb
Rails.application.routes.draw do
	 devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get 'contacts/upload', to: 'contacts#upload', as: 'upload'
	post 'contacts/import', to: 'contacts#import', as: 'import_create'

  resources :contacts do
		resources :gifts
	end

	resources :lists
	resources :groups
	resources :gifts

	get '/dashboard', to: 'dashboard#index', as: 'dashboard'

	authenticated :user do
		root 'dashboard#index', as: :authenticated_root
	end

	root to: 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	## allows me to set devise & external page layouts
	layout :layout_by_resource

	include DeviseWhitelist

	def layout_by_resource
		if devise_controller?
			"pages"
		else
			"application"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
    case level
        when :notice then "notice is-primary"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/views/application/_navbar.html.erb
<% if controller_name == "sessions" || controller_name == 'registrations' || controller_name == 'pages' %>

<div class="hero-head">
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a role="button" id="burger" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-turbolinks-permanent>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-menu">
      <div class="navbar-end">
        <div class="tabs is-right">
          <% if current_user %>
            <ul>
              <li><%= link_to "Import Contacts", upload_path, method: :GET, class: "navbar-item" %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item is-active' %></li>
          </ul>
          <% else %>
            <ul>
              <li><%= link_to "Login", new_user_session_path, method: :GET, class: 'navbar-item' %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, method: :GET, class: 'navbar-item' %></li>
            </ul>
          <% end %>
        </div>
      </div>
      </div>
    </div>
    </nav>
  </div>

<% else %>

    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
            <%= link_to image_tag('garden_64.png'), dashboard_path, class: 'navbar-item' %>
          <a role="button" id="burger" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-turbolinks-permanent>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div class="navbar-menu">
          <div class="navbar-end">
            <div class="tabs is-right">
              <% if current_user %>
                <ul>
                  <li><%= link_to "Import Contacts", upload_path, method: :GET, class: "navbar-item" %></li>
                  <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-item is-active' %></li>
                </ul>
              <% else %>
                <ul>
                  <li> <%= link_to "Login", new_user_session_path, method: :GET, class: 'navbar-item' %></li>
                  <li><%= link_to "Sign Up", new_user_registration_path, method: :GET, class: 'navbar-item' %></li>
                <ul>
              <% end %>
            </div>
          </div>
          </div>
        </div>
      </div>
    </nav>









<% end %>

app/views/application/_pages_navbar.html.erb
<section class="container pages_navbar">
	<div class="tabs is-medium pages-navbar-tabs">
		<ul>
			<li id="dashboard"><%= link_to 'Dashboard', dashboard_path %></li>
			<li id="contacts"><%= link_to 'Contacts', contacts_path%></li>
			<li id="lists"><%= link_to 'Lists', lists_path%></li>
			<li id="gifts"><%= link_to 'Gifts', gifts_path%></li>
		</ul>
	</div>
</section>